version: 2.1
orbs:
  node: circleci/node@5.0.3

# commands:
#   install_synpress:
#     steps:
#       - run:
#           name: Install Synpress
#           command: npm i @synthetixio/synpress

jobs:
  synpress-test:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/app
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      # - install_synpress
      - run:
          name: Run Test
          command: yarn test:e2e:ci
          no_output_timeout: 30m

workflows:
  test_my_app:
    jobs:
      - synpress-test